### ISSUE TITLE
RegShift::into_shift is private, meaning you can never convert a RegShift operand value into a RegShiftStyle value.

### ISSUE THREAD

**Issue by WarpspeedSCP** [iximeow/yaxpeax-arm#10]
I am trying to process operand types for instructions with armv7, and I noticed there's no way to actually convert a RegShift value into a RegShiftStyle one. The function to do so is not marked public:

https://github.com/iximeow/yaxpeax-arm/blob/8898f9cca4ec96734929d4a2c11435b9f825aec8/src/armv7.rs#L1108-L1114

Was this intentional?

**Comment by iximeow** [comment]
oh yeah, that's pretty awkward. `into_shift` is used for the display (and related) impl and why this didn't show up as a dead code warning. #11 is, of course, the right thing to do here.

i apparently also never released 0.2.4 which includes a few fixes in armv7 decoding (both arm mode and thumb mode), so i'll pull in your patch in #11 and do that. thank you!

**Comment by iximeow** [comment]
and published: https://crates.io/crates/yaxpeax-arm/0.2.4 . if you run into anything else (good or bad) with the decoder please let me know!

**Comment by WarpspeedSCP** [comment]
nice, now I can update!
