### ISSUE TITLE
Fails to disassemble negative branches

### ISSUE THREAD

**Issue by pr0me** [iximeow/yaxpeax-arm#6]
The disassembler fails to correctly decode branches (B as well as BL) with negative offsets, 
such as `b.w #-0xc308` / `b.w #0xffff3cfc` (these are equivalent):
```rust
fn main() {
    // b #-0xc308
    let data = [0xf3, 0xf7, 0x7c, 0xbe];
    let mut reader = yaxpeax_arch::U8Reader::new(&data[..]);
    let instr = match InstDecoder::default_thumb().decode(&mut reader) {
        Err(e) => {
            panic!("failed to decode {:#x?}: {}", data, e)
        }
        Ok(instr) => instr,
    };

    println!("{}", instr);
}
```

The error code is: `undefined encoding`.

**Comment by iximeow** [comment]
@/ehntoo included a test case for this in #8, which is now merged - sorry this one sat around so long, i've apparently been missing github email notifications for quite a while...
